-- Search alias patch: 71 products
UPDATE "Product" SET "searchAliases" = 'toor, arhar, tur, thuvaram, kandi, pigeon pea' WHERE lower(trim(name)) = lower(trim('Natural Hair Dye'));
UPDATE "Product" SET "searchAliases" = 'toor, arhar, tur, thuvaram, kandi, pigeon pea' WHERE lower(trim(name)) = lower(trim('Natural Henna Powder'));
UPDATE "Product" SET "searchAliases" = 'ashwagandha, winter cherry, amukkara, asgandh' WHERE lower(trim(name)) = lower(trim('Ashwagandha powder'));
UPDATE "Product" SET "searchAliases" = 'gur, jaggery, guda, vellam, bellam, sakhar' WHERE lower(trim(name)) = lower(trim('Palm Jaggery'));
UPDATE "Product" SET "searchAliases" = 'flax, alsi, linseed, agase, avise vittu, flax seed' WHERE lower(trim(name)) = lower(trim('Flax Seed Powder'));
UPDATE "Product" SET "searchAliases" = 'gur, jaggery, guda, vellam, bellam, sakhar' WHERE lower(trim(name)) = lower(trim('Date Palm Jaggery'));
UPDATE "Product" SET "searchAliases" = 'gur, guda, vellam, bellam, sakhar' WHERE lower(trim(name)) = lower(trim('Jaggery'));
UPDATE "Product" SET "searchAliases" = 'gur, jaggery, guda, vellam, bellam, sakhar' WHERE lower(trim(name)) = lower(trim('Jaggery Powder'));
UPDATE "Product" SET "searchAliases" = 'gur, jaggery, guda, vellam, bellam, sakhar' WHERE lower(trim(name)) = lower(trim('jaggery Fine Powder'));
UPDATE "Product" SET "searchAliases" = 'toor, arhar, tur, thuvaram, kandi, pigeon pea' WHERE lower(trim(name)) = lower(trim('Natural Camphor'));
UPDATE "Product" SET "searchAliases" = 'neem, veppam, vepa, bevu, azadirachta' WHERE lower(trim(name)) = lower(trim('Neem Leaves Powder'));
UPDATE "Product" SET "searchAliases" = 'flax, alsi, linseed, agase, avise vittu' WHERE lower(trim(name)) = lower(trim('Flax Seed'));
UPDATE "Product" SET "searchAliases" = 'brahmi, bacopa, neer brahmi, mandookaparni' WHERE lower(trim(name)) = lower(trim('Brahmi Powder'));
UPDATE "Product" SET "searchAliases" = 'amla, gooseberry, indian gooseberry, nellikai, usiri, amalaki' WHERE lower(trim(name)) = lower(trim('Amla Powder'));
UPDATE "Product" SET "searchAliases" = 'sarson, rai, mustard, ava, kadugu, avalu' WHERE lower(trim(name)) = lower(trim('Mustard Oil'));
UPDATE "Product" SET "searchAliases" = 'peanut, groundnut, verkadalai, pallilu, shenga, nilakadala' WHERE lower(trim(name)) = lower(trim('Groundnut Oil'));
UPDATE "Product" SET "searchAliases" = 'little millet, samai, kutki, same, chama, gingelly, til, ellu, nuvvulu, sesame, sesame seed' WHERE lower(trim(name)) = lower(trim('Sesame Oil'));
UPDATE "Product" SET "searchAliases" = 'peanut, groundnut, verkadalai, pallilu, shenga, nilakadala' WHERE lower(trim(name)) = lower(trim('Groundnut Cake'));
UPDATE "Product" SET "searchAliases" = 'peanut, groundnut, verkadalai, pallilu, shenga, nilakadala' WHERE lower(trim(name)) = lower(trim('Fried Groundnuts'));
UPDATE "Product" SET "searchAliases" = 'ragi, nachni, ragulu, kezhvaragu, mandua, finger millet' WHERE lower(trim(name)) = lower(trim('Finger Millet Ravva'));
UPDATE "Product" SET "searchAliases" = 'foxtail, korra, kakum, navane, thinai, kangni' WHERE lower(trim(name)) = lower(trim('Foxtail Millet Flour'));
UPDATE "Product" SET "searchAliases" = 'barnyard, sanwa, jhangora, oodalu, kuthiraivali' WHERE lower(trim(name)) = lower(trim('Barnyard Millet Ravva'));
UPDATE "Product" SET "searchAliases" = 'ragi, nachni, ragulu, kezhvaragu, mandua, finger millet' WHERE lower(trim(name)) = lower(trim('Finger Millet Poha'));
UPDATE "Product" SET "searchAliases" = 'foxtail, korra, kakum, navane, thinai, kangni' WHERE lower(trim(name)) = lower(trim('Foxtail Millet'));
UPDATE "Product" SET "searchAliases" = 'barnyard, sanwa, jhangora, oodalu, kuthiraivali' WHERE lower(trim(name)) = lower(trim('Barnyard Millet Flour'));
UPDATE "Product" SET "searchAliases" = 'ragi, nachni, ragulu, kezhvaragu, mandua' WHERE lower(trim(name)) = lower(trim('Finger Millet'));
UPDATE "Product" SET "searchAliases" = 'barnyard, sanwa, jhangora, oodalu, kuthiraivali' WHERE lower(trim(name)) = lower(trim('Barnyard Millet Poha'));
UPDATE "Product" SET "searchAliases" = 'barnyard, sanwa, jhangora, oodalu, kuthiraivali' WHERE lower(trim(name)) = lower(trim('Barnyard Millet'));
UPDATE "Product" SET "searchAliases" = 'samai, kutki, same, chama' WHERE lower(trim(name)) = lower(trim('Little Millet'));
UPDATE "Product" SET "searchAliases" = 'kodo, varagu, arikelu, kodra, harka' WHERE lower(trim(name)) = lower(trim('Kodo Millet Flour'));
UPDATE "Product" SET "searchAliases" = 'proso, barri, panivaragu, chena, variga' WHERE lower(trim(name)) = lower(trim('Proso Millet'));
UPDATE "Product" SET "searchAliases" = 'little millet, samai, kutki, same, chama' WHERE lower(trim(name)) = lower(trim('Little Millet Flour'));
UPDATE "Product" SET "searchAliases" = 'sarson, rai, mustard, ava, kadugu, avalu' WHERE lower(trim(name)) = lower(trim('Multigrain Malt Flour'));
UPDATE "Product" SET "searchAliases" = 'little millet, samai, kutki, same, chama' WHERE lower(trim(name)) = lower(trim('Little Millet Ravva'));
UPDATE "Product" SET "searchAliases" = 'proso, barri, panivaragu, chena, variga' WHERE lower(trim(name)) = lower(trim('Proso Millet Flour'));
UPDATE "Product" SET "searchAliases" = 'proso, barri, panivaragu, chena, variga' WHERE lower(trim(name)) = lower(trim('Proso Millet Ravva'));
UPDATE "Product" SET "searchAliases" = 'foxtail, korra, kakum, navane, thinai, kangni' WHERE lower(trim(name)) = lower(trim('Foxtail Millet Ravva'));
UPDATE "Product" SET "searchAliases" = 'kodo, varagu, arikelu, kodra, harka' WHERE lower(trim(name)) = lower(trim('Kodo Millet Poha'));
UPDATE "Product" SET "searchAliases" = 'sarson, rai, mustard, ava, kadugu, avalu' WHERE lower(trim(name)) = lower(trim('Multi grain Atta'));
UPDATE "Product" SET "searchAliases" = 'sarson, rai, mustard, ava, kadugu, avalu' WHERE lower(trim(name)) = lower(trim('Sambhava wheat flour'));
UPDATE "Product" SET "searchAliases" = 'laung, clove, lavanga, grambu, lavangalu' WHERE lower(trim(name)) = lower(trim('Cloves'));
UPDATE "Product" SET "searchAliases" = 'sarson, rai, mustard, ava, kadugu, avalu' WHERE lower(trim(name)) = lower(trim('Sambhava wheat rawa'));
UPDATE "Product" SET "searchAliases" = 'dhania, coriander, kothmir, malli, kothimeera' WHERE lower(trim(name)) = lower(trim('Coriander Leaf Pickle'));
UPDATE "Product" SET "searchAliases" = 'sarson, rai, mustard, ava, kadugu, avalu' WHERE lower(trim(name)) = lower(trim('Navara Rice'));
UPDATE "Product" SET "searchAliases" = 'foxtail, korra, kakum, navane, thinai, kangni' WHERE lower(trim(name)) = lower(trim('Andukorra Papad'));
UPDATE "Product" SET "searchAliases" = 'elaichi, yelakki, elakkai, elakulu' WHERE lower(trim(name)) = lower(trim('Cardamom'));
UPDATE "Product" SET "searchAliases" = 'amla, gooseberry, indian gooseberry, nellikai, usiri, amalaki' WHERE lower(trim(name)) = lower(trim('Amla pickle'));
UPDATE "Product" SET "searchAliases" = 'moringa, drumstick, murungai, munaga, shevga, sahjan' WHERE lower(trim(name)) = lower(trim('Moringa Powder spicy'));
UPDATE "Product" SET "searchAliases" = 'toor, arhar, tur, thuvaram, kandi, pigeon pea, haldi, turmeric, arisina, manjal, pasupu, halad' WHERE lower(trim(name)) = lower(trim('Kasturi Turmeric'));
UPDATE "Product" SET "searchAliases" = 'sarson, rai, mustard, ava, kadugu, avalu' WHERE lower(trim(name)) = lower(trim('Mustard'));
UPDATE "Product" SET "searchAliases" = 'toor, arhar, tur, thuvaram, kandi, pigeon pea' WHERE lower(trim(name)) = lower(trim('Kandi Powder'));
UPDATE "Product" SET "searchAliases" = 'gur, jaggery, guda, vellam, bellam, sakhar' WHERE lower(trim(name)) = lower(trim('Gongura Pickle'));
UPDATE "Product" SET "searchAliases" = 'peanut, groundnut, verkadalai, pallilu, shenga, nilakadala' WHERE lower(trim(name)) = lower(trim('Groundnut Chutney Powder'));
UPDATE "Product" SET "searchAliases" = 'adrak, ginger, allam, inji, shunti' WHERE lower(trim(name)) = lower(trim('Ginger pickle'));
UPDATE "Product" SET "searchAliases" = 'flax, alsi, linseed, agase, avise vittu, flax seed' WHERE lower(trim(name)) = lower(trim('Flaxseed Burfie'));
UPDATE "Product" SET "searchAliases" = 'peanut, groundnut, verkadalai, pallilu, shenga, nilakadala' WHERE lower(trim(name)) = lower(trim('Groundnut Laddu'));
UPDATE "Product" SET "searchAliases" = 'peanut, groundnut, verkadalai, pallilu, shenga, nilakadala' WHERE lower(trim(name)) = lower(trim('Groundnut Masala'));
UPDATE "Product" SET "searchAliases" = 'honey, madhu, shahad, then, tene' WHERE lower(trim(name)) = lower(trim('Forest Honey'));
UPDATE "Product" SET "searchAliases" = 'peanut, groundnut, verkadalai, pallilu, shenga, nilakadala' WHERE lower(trim(name)) = lower(trim('Chikki Groundnut'));
UPDATE "Product" SET "searchAliases" = 'kodo, varagu, arikelu, kodra, harka' WHERE lower(trim(name)) = lower(trim('Kodo Millet'));
UPDATE "Product" SET "searchAliases" = 'kodo, varagu, arikelu, kodra, harka' WHERE lower(trim(name)) = lower(trim('Kodo Millet Ravva'));
UPDATE "Product" SET "searchAliases" = 'toor, arhar, tur, thuvaram, kandi, pigeon pea, haldi, turmeric, arisina, manjal, pasupu, halad' WHERE lower(trim(name)) = lower(trim('Turmeric Powder'));
UPDATE "Product" SET "searchAliases" = 'cumin, jeerige, jilakara, seeragam' WHERE lower(trim(name)) = lower(trim('Jeera'));
UPDATE "Product" SET "searchAliases" = 'dalchini, dalchina chakke, pattai, lavangapattai' WHERE lower(trim(name)) = lower(trim('Cinnamon'));
UPDATE "Product" SET "searchAliases" = 'ragi, nachni, ragulu, kezhvaragu, mandua, finger millet' WHERE lower(trim(name)) = lower(trim('Finger Millet Flour'));
UPDATE "Product" SET "searchAliases" = 'foxtail, korra, kakum, navane, thinai, kangni' WHERE lower(trim(name)) = lower(trim('Foxtail Millet Poha'));
UPDATE "Product" SET "searchAliases" = 'peanut, groundnut, verkadalai, pallilu, shenga, nilakadala' WHERE lower(trim(name)) = lower(trim('Groundnut Seed'));
UPDATE "Product" SET "searchAliases" = 'gur, jaggery, guda, vellam, bellam, sakhar' WHERE lower(trim(name)) = lower(trim('jaggery Small Balls'));
UPDATE "Product" SET "searchAliases" = 'jeera, cumin, jeerige, jilakara, seeragam' WHERE lower(trim(name)) = lower(trim('Jeera powder'));
UPDATE "Product" SET "searchAliases" = 'sendha namak, himalayan salt, saindhava, induppu' WHERE lower(trim(name)) = lower(trim('Rock Salt'));
UPDATE "Product" SET "searchAliases" = 'sarson, rai, mustard, ava, kadugu, avalu' WHERE lower(trim(name)) = lower(trim('Sambhava wheat'));
